blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	# post urls
	path('', views.post_list, name='post_list'),
	path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
	path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
	def get_queryset(self):
		return super(PublishedManager, self).get_queryset().filter(status='published')

class Post(models.Model):
	STATUS_CHOICES = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
	title = models.CharField(max_length=250)
	lead = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250, unique_for_date='publish')
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
	body = models.TextField()
	publish = models.DateTimeField(default=timezone.now)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

	tags = TaggableManager()
	objects = models.Manager() # the default manager
	published = PublishedManager() # custom manager

	class Meta:
		ordering = ('-publish',)

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post_detail',
						args=[self.publish.year,
								self.publish.month,
								self.publish.day,
								self.slug])

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from .models import Post

from taggit.models import Tag

# Post list view
def post_list(request, tag_slug=None):
	object_list = Post.published.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		object_list = object_list.filter(tags__in=[tag])

	paginator = Paginator(object_list, 5)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer - deliver the first page
		posts = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page of results
		posts = paginator.paginator(paginator.num_pages)

	return render(request, 'blog/list.html', {'page': page,
												'posts': posts,
												'tag': tag})

# Post detail view
def post_detail(request, year, month, day, post):
	post = get_object_or_404(Post, slug=post,
									status='published',
									publish__year=year,
									publish__month=month,
									publish__day=day)

	# List of similar posts
	post_tags_ids = post.tags.values_list('id', flat=True)
	similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:3]

	return render(request, 'blog/detail.html', {'post': post, 'similar_posts': similar_posts})

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static "blog/blog.css" %}">
</head>
<body>
	<div class="site-container">
		<header class="site-header">
			<h1><a href="{% url 'blog:post_list' %}">🤖 DavidJAbb</a></h1>
		</header>
		<nav class="site-nav">
			<ul>
				<li class="nav-item active"><a href="{% url 'blog:post_list' %}" title="About">Blog</a></li>
				<li class="nav-item"><a href="#" title="About Me">About Me</a></li>
				<li class="nav-item"><a href="#" title="Archive">Archive</a></li>
				<li class="nav-item"><a href="#" title="Search">Search</a></li>
			</ul>
		</nav>
		<main>
			{% block content %}
			{% endblock %}
			{% block sidebar %}
			{% endblock %}
		</main>
		<footer class="site-footer">
			<p>Made by <a href="#">@DavidJAbb</a></p>
		</footer>
	</div>
</body>
</html>

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load static %}
{% load humanize %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
<article>
	<h2 class="post-title">{{ post.title }}</h2>
	<small class="post-info">{{ post.publish|date:"l, j F Y" }}</small>
	{{ post.body|linebreaks }}
	<div class="tags">
		<ul>
			{% for tag in post.tags.all %}
			<li class="tag"><a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag }}</a></li>
			{% endfor %}
		</ul>
	</div>
</article>
{% endblock %}

{% block sidebar %}
{% if similar_posts.count > 0 %}
<div class="related-posts">
	<h3>Related Posts</h3>
	{% for post in similar_posts %}
	<small>{{ post.publish|date:"j F Y" }}</small>
	<p class="related-post"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
	{% endfor %}
</div>
{% endif %}
{% endblock %}

blog/templates/blog/latest_posts.html
{% for post in latest_posts %}
<div>
	<h4>{{ post.publish|date:"j F Y" }}</h4>
	<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
</div>
{% endfor %}

blog/templates/blog/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
{% if tag %}
<h2 class="tag-header">Posts tagged '{{ tag.name }}'</h2>
{% endif %}
{% for post in posts %}
<article>
	<h2 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
	<hr class="post-title-underline">
	<small class="post-info">{{ post.publish|date:"l, j F Y" }}</small>
	{{ post.body|linebreaks|truncatewords:30 }}
	<p><a href="{{ post.get_absolute_url }}">Continue reading</a></p>
</article>
{% endfor %}
{% if page.num_pages > 1 %}
{% include "pagination.html" with page=posts %}
{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
	<ul>
		{% if page.has_previous %}
		<li><a href="?page=1">First</a></li>
		<li><a href="?page={{ page.previous_page_number }}">Previous</a></li>
		{% endif %}

		{% for i in page.paginator.page_range %}
			{% if page.number == i %}
				<li><a class="active" href="?page={{ i }}">{{ i }}</a></li>
			{% elif i > page.number|add:'-3' and i < page.number|add:'3' %}
				<li><a href="?page={{ i }}">{{ i }}</a></li>
			{% endif %}
		{% endfor %}

		{% if page.has_next %}
			<li><a href="?page={{ page.next_page_number }}">Next</a></li>
			<li><a href="?page={{ page.paginator.num_pages }}">Last</a></li>
		{% endif %}
	</ul>
</div>